// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSystem.Backend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicSystem.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicSystem.Backend.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistScore")
                        .HasColumnType("integer")
                        .HasColumnName("artist_score");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("text")
                        .HasColumnName("facebook_url");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer")
                        .HasColumnName("followers_count");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("integer")
                        .HasColumnName("following_count");

                    b.PrimitiveCollection<List<string>>("GalleryUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("gallery_urls");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<bool>("IsDobVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dob_visible");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_live");

                    b.Property<bool>("IsParentalConsentGranted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parental_consent_granted");

                    b.Property<bool>("IsPixVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pix_visible");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<DateTime?>("LiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("live_until");

                    b.Property<double?>("MaxSuggestedCache")
                        .HasColumnType("double precision")
                        .HasColumnName("max_suggested_cache");

                    b.Property<double?>("MinSuggestedCache")
                        .HasColumnType("double precision")
                        .HasColumnName("min_suggested_cache");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("PixKey")
                        .HasColumnType("text")
                        .HasColumnName("pix_key");

                    b.Property<string>("ProfessionalLevel")
                        .HasColumnType("text")
                        .HasColumnName("professional_level");

                    b.Property<string>("ProfileType")
                        .HasColumnType("text")
                        .HasColumnName("profile_type");

                    b.Property<int>("ProfileViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("profile_views_count");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SearchName")
                        .HasColumnType("text")
                        .HasColumnName("search_name");

                    b.Property<bool>("ShowProfessionalBadge")
                        .HasColumnType("boolean")
                        .HasColumnName("show_professional_badge");

                    b.Property<string>("SubType")
                        .HasColumnType("text")
                        .HasColumnName("sub_type");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_plan");

                    b.Property<int>("UnreadMessagesCount")
                        .HasColumnType("integer")
                        .HasColumnName("unread_messages_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_level");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("text")
                        .HasColumnName("youtube_url");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
