// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlsNLevb2Cw2ijIP-za6DcxxCzSaUXiuo',
    appId: '1:108435262492:web:fbf5d95559eb76267923d9',
    messagingSenderId: '108435262492',
    projectId: 'music-system-421ee',
    authDomain: 'music-system-421ee.firebaseapp.com',
    storageBucket: 'music-system-421ee.firebasestorage.app',
    measurementId: 'G-CW5WB9ZZJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVsr5FXg1DZh3v_j4APvEvt_uYaIzM6k',
    appId: '1:108435262492:android:b0c39a2d1753a3567923d9',
    messagingSenderId: '108435262492',
    projectId: 'music-system-421ee',
    storageBucket: 'music-system-421ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJojDOB2UC5Du7YfRgY4BwkxXwZcADrM',
    appId: '1:108435262492:ios:339055b1dc4ed9097923d9',
    messagingSenderId: '108435262492',
    projectId: 'music-system-421ee',
    storageBucket: 'music-system-421ee.firebasestorage.app',
    iosBundleId: 'com.musicapp.musicSystem',
  );
}
